parameters:
    evolution.session.storage.native.class:     Theodo\Evolution\HttpFoundationBundle\Storage\NativeSessionStorage
    evolution.session.storage.mock_file.class:  Theodo\Evolution\HttpFoundationBundle\Storage\MockFileSessionStorage
    evolution.session_listener.class:           Theodo\Evolution\HttpFoundationBundle\Listener\SessionListener

    #Bag managers
    evolution.session.symfony10_bag_manager.class: Theodo\Evolution\HttpFoundationBundle\Manager\Symfony10BagManager

services:
    evolution.session_listener:
        class: %evolution.session_listener.class%
        tags:
            - { name: kernel.event_subscriber, event: kernel.request }
        arguments:
            - @evolution.session.bag_manager

    evolution.session.bag_manager_configuration:
        class: %evolution.session.bag_manager_configuration.class%

    evolution.session.bag_manager:
        class: %evolution.session.bag_manager.class%
        arguments:
            - @evolution.session.bag_manager_configuration
